name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 3.109.1.132
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd DevOpsPrac
            ls
            git pull
            pnpm i
            pnpm run build 
            
            # Kill existing process on port 3000
            sudo fuser -k 3000/tcp || true
            
            # Start application in the background and log output
            nohup pnpm run start > app.log 2>&1 &

            echo "Deployment successful"
